import { useRef, useState, type CSSProperties, type ElementType, type ReactNode } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { ArrowDownRight, ArrowRight, ArrowUpRight, BrainCircuit, BarChart3, CheckCircle2, CloudCog, Layers3, Linkedin, Mail, Network, ShieldCheck, Sparkles, UsersRound } from 'lucide-react';
type FadeProps={children:ReactNode;delay?:number;y?:number;as?:ElementType;className?:string};
function Fade({children,delay=0,y=28,as='div',className=''}:FadeProps){const Tag=motion.create(as);return <Tag className={className} initial={{opacity:0,y}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-40px'}} transition={{duration:.75,delay,ease:[.22,1,.36,1]}}>{children}</Tag>}
function Pill({children}:{children:ReactNode}){return <span className="pill">{children}</span>}
function PrimaryLink({href,children}:{href:string;children:ReactNode}){return <a className="primary-link" href={href}>{children}<ArrowUpRight size={18}/></a>}
function GlobalNav(){const {scrollYProgress}=useScroll();return <header className="global-nav"><nav className="nav-inner" aria-label="Primary navigation"><a className="brand" href="#top"><span>AS</span>AZHARUDDIN SHAIKH</a><div className="nav-links"><a href="#top">Top</a><a href="#about">About</a><a href="#expertise">Expertise</a><a href="#work">Work</a></div><a className="nav-contact" href="mailto:azhar.sheikh92@gmail.com">Let's talk <ArrowUpRight size={16}/></a></nav><motion.div className="scroll-progress" style={{scaleX:scrollYProgress}}/></header>}
const signals=['PROGRAM INTELLIGENCE','AI TRANSFORMATION','KNOWLEDGE SYSTEMS','ENTERPRISE DELIVERY','HUMAN-GOVERNED AI','OPERATIONAL EXCELLENCE'];
const outcomes=[['16+','years transforming complex systems'],['70%','less manual reporting effort'],['40%','improvement in onboarding and time-to-value'],['7,000+','pages continuously evaluated'],['£1.7M+','annual portfolio managed'],['153%','of annual delivery target achieved']];
const capabilities=[
 {n:'01',icon:BrainCircuit,title:'AI Transformation',copy:'Designing explainable, human-governed AI systems that connect reliable data, sound operating models and measurable business action.'},
 {n:'02',icon:BarChart3,title:'Program Intelligence',copy:'Turning fragmented delivery signals into visible risk, decisions, accountable ownership and recovery paths.'},
 {n:'03',icon:Network,title:'AI Knowledge Operations',copy:'Building governed retrieval and intelligence systems that make enterprise knowledge accurate, measurable and usable by people and AI.'},
 {n:'04',icon:CloudCog,title:'Enterprise Delivery',copy:'Leading complex, multi-region programs through dependency governance, readiness controls and calm execution under production risk.'},
 {n:'05',icon:UsersRound,title:'Leadership & Scale',copy:'Building durable teams and operating systems that replace individual heroics with clarity, capacity and repeatable performance.'}
];
const projects=[
 {n:'01',kind:'WORKING PROTOTYPE',title:'Risk Radar',lead:'Explainable program intelligence for earlier, evidence-backed intervention.',copy:'A production-shaped decision-support system that converts structured delivery updates into portfolio health, traceable risk, dependency concentration, scenarios and human-reviewed actions.',stats:['2,520 synthetic updates','12 programs · 180 workstreams','Deterministic scoring baseline'],href:'https://azhar-risk-radar.streamlit.app/',accent:'cyan'},
 {n:'02',kind:'LIVE APPLICATION',title:'Program Intelligence Suite',lead:'From fragmented status noise to executive-ready delivery intelligence.',copy:'A connected system for program health, material risks, decisions, next actions, dependency-aware timelines and recovery scenarios—with humans retained at consequential decision points.',stats:['Dependency-aware timelines','Recovery scenario planning','Human-in-the-loop AI'],href:'https://azhar-program-intelligence.streamlit.app/',accent:'violet'},
 {n:'03',kind:'RAG-BASED MCP',title:'Docs MCP',lead:'Governed enterprise documentation, retrievable directly by AI assistants.',copy:'A machine-accessible retrieval layer that turns static product documentation into structured knowledge. It helps assistants answer with current, governed source material and gives teams faster, evidence-based access to product knowledge.',stats:['RAG retrieval','Governed documentation','Evidence-grounded answers'],href:'#contact',accent:'cyan'},
 {n:'04',kind:'RAG-BASED MCP',title:'Analytics MCP',lead:'Customer signals converted into evidence teams can act on.',copy:'Connects search and behavioral analytics—including zero-result searches, stale content and knowledge gaps—to AI-accessible workflows, helping teams prioritize work using observed customer behavior instead of assumptions.',stats:['Search behavior signals','Content-gap intelligence','Evidence-based prioritization'],href:'#contact',accent:'violet'},
 {n:'05',kind:'OPERATING SYSTEM',title:'Docs Command Center',lead:'One operating layer for delivery, decisions, retrospection and AI initiatives.',copy:'A unified view of milestones, KPIs, OKRs, retrospectives, team information, decisions, the AI Playbook and Idea Lab—designed to reduce fragmentation and preserve organizational learning.',stats:['Program and KPI visibility','Decision tracking','AI initiative governance'],href:'#contact',accent:'orange'}
];
function Hero(){return <section className="hero cinematic-hero" id="top"><div className="grid-noise"/><Fade as="nav" y={-16} className="nav"><a className="brand" href="#top"><span>AS</span>AZHARUDDIN SHAIKH</a><div className="nav-links"><a href="#about">About</a><a href="#expertise">Expertise</a><a href="#work">Work</a></div><a className="nav-contact" href="mailto:azhar.sheikh92@gmail.com">Let's talk <ArrowUpRight size={16}/></a></Fade><div className="hero-copy"><Fade delay={.1}><Pill><Sparkles size={14}/> Mumbai · AI transformation leader</Pill></Fade><Fade as="h1" delay={.2} className="hero-title">FROM COMPLEXITY<br/>TO <span>COORDINATED</span><br/>ACTION.</Fade><Fade as="p" delay={.32} className="hero-lead">AI transformation, knowledge operations, and program leader building explainable systems that convert operational complexity into decisions, ownership and measurable action.</Fade><Fade delay={.45} className="hero-actions"><PrimaryLink href="#work">Explore my work</PrimaryLink><a className="text-link" href="#about">My story <ArrowDownRight size={18}/></a></Fade></div><Fade delay={.55} className="portrait-wrap"><div className="portrait-glow"/><img src="/azhar-hero-cinematic.png" alt="Azharuddin Shaikh in a cinematic enterprise technology setting"/></Fade><div className="hero-index"><span>AI TRANSFORMATION</span><span>PROGRAM LEADERSHIP</span><span>KNOWLEDGE SYSTEMS</span></div></section>}
function SignalBar(){return <section className="signal-bar"><div className="signal-track">{[...signals,...signals].map((s,i)=><span key={i}>{s}<i>✦</i></span>)}</div></section>}
function About(){return <section className="about section-pad" id="about"><div className="section-tag"><span>01</span> THE THROUGH LINE</div><div className="about-grid"><Fade as="h2" className="display-title">I BUILD<br/>SYSTEMS,<br/><em>NOT HEROICS.</em></Fade><div className="about-copy"><Fade><p className="statement">I work at the intersection of knowledge, technology and program delivery—turning scattered technical information and complex workflows into systems that people and AI can use confidently.</p></Fade><Fade delay={.12}><p>My strength is bringing structure to ambiguous problems. I connect Product, Engineering, UX, Support, Customer Success and content teams; establish clear ownership and governance; surface risks and dependencies; and move initiatives from business problem to practical, scalable solution.</p></Fade><Fade delay={.2}><p>I’m particularly interested in accurate, accessible and measurable enterprise knowledge, alongside the operating systems behind the work: roadmaps, decision records, dashboards, KPIs, approval workflows, risk controls and feedback loops.</p></Fade><Fade delay={.26} className="credentials"><Pill>Gen AI Mastermind Certified</Pill><Pill>Certified ScrumMaster</Pill><Pill>B.E. Information Technology</Pill></Fade><Fade delay={.3}><a className="inline-arrow" href="https://linkedin.com/in/iazharshaikh" target="_blank" rel="noreferrer">Follow the full journey <ArrowRight size={18}/></a></Fade></div></div><div className="outcomes">{outcomes.map(([n,t],i)=><Fade key={n} delay={i*.06} className="outcome"><strong>{n}</strong><span>{t}</span></Fade>)}</div></section>}
function Expertise(){return <section className="expertise section-pad" id="expertise"><div className="section-tag light"><span>02</span> WHAT I DO</div><h2 className="display-title dark">SYSTEMS THAT<br/><em>MOVE WORK FORWARD.</em></h2><div className="cap-list">{capabilities.map(({n,icon:Icon,title,copy},i)=><Fade className="cap-row" key={n} delay={i*.06}><span className="cap-num">{n}</span><Icon className="cap-icon"/><h3>{title}</h3><p>{copy}</p><ArrowUpRight className="cap-arrow"/></Fade>)}</div></section>}
const ENABLE_RISK_SIMULATOR=true;
const scenarios={
 Stable:{dependency:82,capacity:88,pressure:28},
 'Vendor delay':{dependency:28,capacity:76,pressure:68},
 'Scope increase':{dependency:58,capacity:42,pressure:82}
};
type ScenarioName=keyof typeof scenarios;
function RiskSimulator(){const [active,setActive]=useState<ScenarioName|null>('Stable');const [signals,setSignals]=useState({...scenarios.Stable});const score=Math.round((100-signals.dependency)*.38+(100-signals.capacity)*.27+signals.pressure*.35);const state=score<35?{tone:'stable',title:'Program is stable',action:'Maintain cadence and monitor vendor milestones.'}:score<60?{tone:'watch',title:'Delivery friction emerging',action:'Clarify ownership, protect capacity, and review dependencies.'}:{tone:'critical',title:'Intervention recommended',action:'Escalate the decision, model recovery options, and re-baseline.'};const choose=(name:ScenarioName)=>{setActive(name);setSignals({...scenarios[name]})};return <div className={`risk-simulator ${state.tone}`} onPointerMove={e=>e.stopPropagation()}><div className="sim-top"><span>INTERACTIVE / SIGNAL MODEL</span><span className="model-live"><i/> MODEL ACTIVE</span></div><div className="sim-main"><div className="signal-controls">{([['dependency','Dependency confidence'],['capacity','Team capacity'],['pressure','Schedule pressure']] as const).map(([key,label])=><label key={key}><span>{label}<strong>{signals[key]}%</strong></span><input aria-label={label} type="range" min="0" max="100" value={signals[key]} onChange={e=>{setActive(null);setSignals({...signals,[key]:Number(e.target.value)})}} style={{'--value':`${signals[key]}%`} as CSSProperties}/></label>)}</div><div className="score-dial"><motion.strong key={score} initial={{opacity:0,scale:.72,y:8}} animate={{opacity:1,scale:1,y:0}}>{score}</motion.strong><span>RISK SCORE</span></div></div><div className="scenario-buttons">{(Object.keys(scenarios) as ScenarioName[]).map(name=><button className={active===name?'active':''} onClick={()=>choose(name)} key={name}>{name}</button>)}</div><motion.div className="diagnosis" key={state.title} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><div><small>AI-ASSISTED DIAGNOSIS</small><strong>{state.title}</strong></div><div><small>RECOMMENDED ACTION</small><p>{state.action}</p></div></motion.div></div>}
function ProjectCard({p,index}:{p:typeof projects[number];index:number}){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const scale=useTransform(scrollYProgress,[0,.65,1],[1,1,1-(projects.length-1-index)*.025]);const showSimulator=p.title==='Risk Radar'&&ENABLE_RISK_SIMULATOR;return <div className={`project-shell ${showSimulator?'simulator-shell':''}`} ref={ref}><motion.article className={`project-card ${p.accent} ${showSimulator?'has-simulator':''}`} style={{scale,top:`calc(92px + ${index*22}px)`}} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--card-x',`${((e.clientX-r.left)/r.width)*100}%`);e.currentTarget.style.setProperty('--card-y',`${((e.clientY-r.top)/r.height)*100}%`);e.currentTarget.style.setProperty('--tilt-x',`${((e.clientY-r.top)/r.height-.5)*-8}deg`);e.currentTarget.style.setProperty('--tilt-y',`${((e.clientX-r.left)/r.width-.5)*10}deg`)}} onPointerLeave={e=>{e.currentTarget.style.setProperty('--tilt-x','0deg');e.currentTarget.style.setProperty('--tilt-y','0deg')}}><div className="project-head"><span className="project-num">{p.n}</span><Pill>{p.kind}</Pill><h3>{p.title}</h3><a href={p.href} target={p.href.startsWith('http')?'_blank':undefined} rel="noreferrer"><ArrowUpRight/></a></div><div className="project-body"><div><p className="project-lead">{p.lead}</p><p className="project-copy">{p.copy}</p></div>{showSimulator?<RiskSimulator/>:<div className="project-visual"><div className="orbit one"/><div className="orbit two"/><Layers3 size={72}/><span>{p.title}</span></div>}</div><div className="project-stats">{p.stats.map(s=><span key={s}><CheckCircle2 size={16}/>{s}</span>)}</div></motion.article></div>}
function Work(){return <section className="work section-pad" id="work"><div className="section-tag"><span>03</span> SELECTED SYSTEMS</div><h2 className="display-title">EVIDENCE<br/><em>IN MOTION.</em></h2><p className="work-intro">Selected systems that make complexity observable, decisions explainable and action accountable.</p><div className="projects">{projects.map((p,i)=><ProjectCard p={p} index={i} key={p.n}/>)}</div></section>}
function Journey(){const rows=[['2010—2018','PACKT','Technical leadership → portfolio transformation','£1.7M+ portfolio · 18-person team · time to market reduced from ~270 to under 120 days'],['2018—2022','CONTENTSTACK','Knowledge architecture → customer enablement','14+ stakeholders · governed cross-functional backlog · stabilized in 6–8 months'],['2022—2023','ACCENTURE / SAP','Enterprise migration delivery','1,000+ contributors · 11 data centres · final 7 migrations · zero missed cutovers'],['2023—NOW','CONTENTSTACK','AI transformation → knowledge systems','7,000+ pages · MCP capabilities · analytics-connected content decisions']];return <section className="journey section-pad"><div className="section-tag"><span>04</span> TRANSFORMATION AT SCALE</div><div className="journey-grid"><Fade><h2 className="display-title">TECHNICAL<br/>DEPTH TO<br/><em>ENTERPRISE IMPACT.</em></h2></Fade><div className="timeline">{rows.map((x,i)=><Fade className="timeline-row" key={x[0]} delay={i*.08}><span>{x[0]}</span><div><h3>{x[1]}</h3><h4>{x[2]}</h4><p>{x[3]}</p></div></Fade>)}</div></div></section>}
function Contact(){return <footer className="contact section-pad" id="contact"><div className="contact-orb"><ShieldCheck/></div><Fade><Pill>OPEN TO THE RIGHT CONVERSATION</Pill><h2>LET'S TURN<br/><span>COMPLEXITY</span><br/>INTO IMPACT.</h2><p>For AI transformation, program leadership, knowledge systems and enterprise delivery opportunities.</p><div className="contact-actions"><PrimaryLink href="mailto:azhar.sheikh92@gmail.com"><Mail size={18}/> Email me</PrimaryLink><a className="social" href="https://linkedin.com/in/iazharshaikh" target="_blank" rel="noreferrer"><Linkedin size={18}/> LinkedIn</a></div></Fade><div className="footer-line"><span>AZHARUDDIN SHAIKH © 2026</span><span>MUMBAI, INDIA</span><a href="#top">BACK TO TOP ↑</a></div></footer>}
export default function App(){return <main onPointerMove={e=>{e.currentTarget.style.setProperty('--mouse-x',`${e.clientX}px`);e.currentTarget.style.setProperty('--mouse-y',`${e.clientY}px`)}}><div className="cursor-light"/><GlobalNav/><Hero/><SignalBar/><About/><Expertise/><Work/><Journey/><Contact/></main>}
